=== RachitDesai/Car-Rental-System/Customer.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="CarRental">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Customer" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:integer"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="age" type="myage"/>
							<xs:element name="email" type="email"/> 
							<xs:element name="mobile" type="phone"/>
						</xs:sequence>
                    </xs:complexType>
                </xs:element>

				<xs:element name="Vehicle" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Number" type="xs:string"/>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Type" type="xs:string"/> 
							<xs:element name="Fare" type="xs:integer"/>
						</xs:sequence>
					 </xs:complexType>
				</xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="myage">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="10"/>
    	<xs:maxExclusive value="70"/>
    </xs:restriction>
</xs:simpleType>
	<xs:simpleType name="email"> 
    <xs:restriction base="xs:string"> 
      <xs:pattern value="[^@]+@[^\.]+\..+"/> 
    </xs:restriction> 
</xs:simpleType>

<xs:simpleType name="phone">
    <xs:restriction base="xs:string">
         <xs:pattern value="[0-9]{10}"/>
    </xs:restriction>
</xs:simpleType>


</xs:schema>

=== RachitDesai/Car-Rental-System/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Customer.xsl"?>
<CarRental  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="customer.xsd">


    <Customer>
        <id>501</id>
        <name>Rachit</name>
        <age>51</age>
        <email>rachit@gmail.com</email>
        <mobile>9898026206</mobile>
    </Customer>
	
    <Customer>
        <id>502</id>
        <name>Ginni</name>
        <age>17</age>
        <email>ginni@gmail.com</email>
        <mobile>1231226206</mobile>
    </Customer>

    <Customer>
        <id>503</id>
        <name>Rammana</name>
        <age>27</age>
        <email>rama@gmail.com</email>
        <mobile>1234226206</mobile>
    </Customer>

    <Customer>
        <id>504</id>
        <name>Meghna</name>
        <age>80</age>
        <email>meghna@gmail.com</email>
        <mobile>9586038522</mobile>
    </Customer>

     <Customer>
        <id>505</id>
        <name>Ravi</name>
        <age>20</age>
        <email>ravi@gmail.com</email>
        <mobile>9909405933</mobile>
    </Customer>




 <Vehicle>
    <Number>KA02AA1234</Number>
    <Name>Innova</Name>
    <Type>Car</Type >
    <Fare>2000</Fare>
</Vehicle>

  
 <Vehicle>
    <Number>KA02AA5678</Number>
    <Name>Bullet</Name>
    <Type>Bike</Type >
    <Fare>500</Fare>
</Vehicle>

  
 <Vehicle>
    <Number>KA02BC1209</Number>
    <Name>Swift</Name>
    <Type>Car</Type >
    <Fare>1000</Fare>
</Vehicle>


   
 <Vehicle>
    <Number>KA02AA6704</Number>
    <Name>Activa</Name>
    <Type>Scooter</Type >
    <Fare>300</Fare>
</Vehicle>


   
 <Vehicle>
    <Number>KA02AA1234</Number>
    <Name>XUV</Name>
    <Type>Car</Type >
    <Fare>2000</Fare>
</Vehicle>


  
 <Vehicle>
    <Number>KA02AA1234</Number>
    <Name>R15</Name>
    <Type>Bike</Type >
    <Fare>800</Fare>
</Vehicle>

 </CarRental>
