=== RachitDesai/Car-Rental-System/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Company">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Emp-Name" type="xs:string"/>
							<xs:element name="Emp-age" type="xs:integer"/>
                            <xs:element name="Emp-salary" type="salary"/>
							<xs:element name="Emp-Email" type="xs:string"/> 
							<xs:element name="Emp-phone" type="xs:integer"/>
							<xs:element name="Emp-designation" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="Emp-Id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="salary">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="50000"/>
    	<xs:maxExclusive value="200000"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== RachitDesai/Car-Rental-System/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="employee.xsd">
   
   <Employee>
   <Emp-ID>1</Emp-ID>
    <Emp-Name>Ginni</Emp-Name>
    <Emp-age>28</Emp-age>
    <Emp-salary>70000</Emp-salary>
    <Emp-Email>ginni@gmail.com</Emp-Email>
    <Emp-phone>1234567890</Emp-phone>
    <Emp-designation>HR</Emp-designation>
   
   </Employee>

   <Employee>
   <Emp-ID>2</Emp-ID>
    <Emp-Name>Rachit</Emp-Name>
    <Emp-age>23</Emp-age>
    <Emp-salary>100000</Emp-salary>
    <Emp-Email>rachit@gmail.com</Emp-Email>
    <Emp-phone>80000022323</Emp-phone>
    <Emp-designation>manager</Emp-designation>
   </Employee>

   <Employee>
   <Emp-ID>3</Emp-ID>
    <Emp-Name>Rahul</Emp-Name>
    <Emp-age>33</Emp-age>
    <Emp-salary>80000</Emp-salary>
    <Emp-Email>r@gmail.com</Emp-Email>
    <Emp-phone>8234567890</Emp-phone>
    <Emp-designation>HR</Emp-designation>
   </Employee>

   <Employee>
   <Emp-ID>4</Emp-ID>
    <Emp-Name>Shohaib</Emp-Name>
    <Emp-age>53</Emp-age>
    <Emp-salary>60000</Emp-salary>
    <Emp-Email>rachit@gmail.com</Emp-Email>
    <Emp-phone>1234567890</Emp-phone>
    <Emp-designation>GM</Emp-designation>
   </Employee>

   <Employee>
   <Emp-ID>5</Emp-ID>
    <Emp-Name>Kumar</Emp-Name>
    <Emp-age>43</Emp-age>
    <Emp-salary>90000</Emp-salary>
    <Emp-Email>kumar@gmail.com</Emp-Email>
    <Emp-phone>16754567890</Emp-phone>
    <Emp-designation>HR</Emp-designation>
   </Employee>

</Company>
